---
language: "node_js"
node_js:
  - "10"
  - "11"
install: npm install
script:
  - npm test
jobs:
  include:
  deploy:
    provider: npm
    email: "$EMAIL_ADDRESS"
    api_key: "$API_KEY"
    skip_cleanup: true
    branches:
      only:
        - master
